name: Build and Push Docker Image

on:
  push:
    #    branches:
    #      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: pcaracal
          password: ${{ secrets.GHCR_PAT }}

      - name: Get tag name
        id: get_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/*/})"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/pcaracal/m324_devops_test_refcard02:${{ steps.get_tag.outputs.tag }}
  
  #  build:
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #
  #      - name: Login to Docker Hub
  #        uses: docker/login-action@v1
  #        with:
  #          username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #
  #      - name: Build and push Docker image
  #        uses: docker/build-push-action@v2
  #        with:
  #          context: .
  #          push: true
  #          tags: hashcatt/m324_devops_test_refcard02:latest
  #  
  
  