name: Build and Push Docker Image

on:
  push:
    #    branches:
    #      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: pcaracal
          password: ${{ secrets.GHCR_PAT }}

      - name: Get tag name
        id: get_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/*/})"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/pcaracal/m324_devops_test_refcard02:${{ steps.get_tag.outputs.tag }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          body: |
            Automated release
            Docker image: https://ghcr.io/pcaracal/m324_devops_test_refcard02:${{ steps.get_tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image to AWS ECR
        run: |
          docker tag ghcr.io/pcaracal/m324_devops_test_refcard02:${{ steps.get_tag.outputs.tag }} ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }}:${{ steps.get_tag.outputs.tag }}
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }}:${{ steps.get_tag.outputs.tag }}
  
  
  #  build:
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #
  #      - name: Login to Docker Hub
  #        uses: docker/login-action@v1
  #        with:
  #          username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #
  #      - name: Build and push Docker image
  #        uses: docker/build-push-action@v2
  #        with:
  #          context: .
  #          push: true
  #          tags: hashcatt/m324_devops_test_refcard02:latest
  #  
  
  